

export const PERMISSIONS = {
    USER: 'USER',
    VIEW_COMPANIES: 'VIEW_COMPANIES',
    VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
    VIEW_ROLES: 'VIEW_ROLES',
    VIEW_ATTESTATIONS: 'VIEW_ATTESTATIONS',
    VIEW_INSUREDS: 'VIEW_INSUREDS',
    VIEW_DEMANDS: 'VIEW_DEMANDS',
    VIEW_LINKED_ENTITIES_SUPERIOR: 'VIEW_LINKED_ENTITIES_SUPERIOR',
    VIEW_LINKED_COMPANIES: 'VIEW_LINKED_COMPANIES',
    VIEW_BROKER_POINTS_OF_SALE: 'VIEW_LINKED_BROKER',
    CREATE_POINT_OF_SALE: 'CREATE_POINT_OF_SALE',
    GENERATE_ATTESTATION: 'GENERATE_ATTESTATION',

    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    CREATE_INSURED: 'CREATE_INSURED',
    CREATE_ROLE: 'CREATE_ROLE',
    CREATE_DEMAND: 'CREATE_DEMAND',

    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    UPDATE_EMPLOYEE_ROLE: 'UPDATE_EMPLOYEE_ROLE',
    UPDATE_ROLE: 'UPDATE_ROLE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_INSURED: 'UPDATE_INSURED',

    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    DELETE_ROLE: 'DELETE_ROLE',
    DELETE_INSURED: 'DELETE_INSURED',

    LINK_COMPANY: 'LINK_COMPANY',
    UNLINK_COMPANY: 'UNLINK_COMPANY',

    ATTRIBUTE_ATTESTATION: 'ATTRIBUTE_ATTESTATION',
    REVOKE_ATTESTATION: 'REVOKE_ATTESTATION',
    VIEW_ENTITIES_SUPERIOR: 'VIEW_ENTITIES_SUPERIOR',
    VIEW_POINTS_OF_SALE: 'VIEW_POINTS_OF_SALE',
    VIEW_UNLINKED_POINTS_SALE: 'VIEW_UNLINKED_POINTS_SALE',

    CREATE_POINT_SALE: 'CREATE_POINT_SALE',

    UPDATE_POINT_SALE: 'UPDATE_POINT_SALE',

    DELETE_POINT_SALE: 'DELETE_POINT_SALE',

    DELIVER_ATTESTATION: 'DELIVER_ATTESTATION',
    UPDATE_ATTESTATION: 'UPDATE_ATTESTATION'
}