export const PERMISSIONS = {
  // Management Entities
  VIEW_MANAGEMENT_ENTITIES: "VIEW_MANAGEMENT_ENTITIES",
  UPDATE_MANAGEMENT_ENTITIES: "UPDATE_MANAGEMENT_ENTITIES",

  // Products
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  CREATE_PRODUCTS: "CREATE_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  AFFILIATE_PRODUCTS: "AFFILIATE_PRODUCTS",

  // Companies
  VIEW_COMPANIES: "VIEW_COMPANIES",
  VIEW_LINKED_COMPANIES: "VIEW_LINKED_COMPANIES",

  // Market-Level Organizations
  VIEW_MARKET_LEVEL_ORGANIZATIONS: "VIEW_MARKET_LEVEL_ORGANIZATIONS",

  // Brokers
  VIEW_BROKERS: "VIEW_BROKERS",

  // Company-Level Organizations
  VIEW_COMPANY_LEVEL_ORGANIZATIONS: "VIEW_COMPANY_LEVEL_ORGANIZATIONS",
  CREATE_COMPANY_LEVEL_ORGANIZATIONS: "CREATE_COMPANY_LEVEL_ORGANIZATIONS",
  UPDATE_COMPANY_LEVEL_ORGANIZATIONS: "UPDATE_COMPANY_LEVEL_ORGANIZATIONS",
  DELETE_COMPANY_LEVEL_ORGANIZATIONS: "DELETE_COMPANY_LEVEL_ORGANIZATIONS",

  // Points of Sale
  VIEW_POINTS_OF_SALE: "VIEW_POINTS_OF_SALE",
  CREATE_POINTS_OF_SALE: "CREATE_POINTS_OF_SALE",
  UPDATE_POINTS_OF_SALE: "UPDATE_POINTS_OF_SALE",
  DELETE_POINTS_OF_SALE: "DELETE_POINTS_OF_SALE",

  // Users (company or point of sale)
  VIEW_USERS: "VIEW_USERS",
  CREATE_USERS: "CREATE_USERS",
  UPDATE_USERS: "UPDATE_USERS",
  DELETE_USERS: "DELETE_USERS",
  VIEW_USERS_POINTS_OF_SALE: "VIEW_USERS_POINTS_OF_SALE",
  CREATE_USERS_POINTS_OF_SALE: "CREATE_USERS_POINTS_OF_SALE",
  UPDATE_USERS_POINTS_OF_SALE: "UPDATE_USERS_POINTS_OF_SALE",
  DELETE_USERS_POINTS_OF_SALE: "DELETE_USERS_POINTS_OF_SALE",

  // Profiles
  CREATE_PROFILES: "CREATE_PROFILES",
  UPDATE_PROFILES: "UPDATE_PROFILES",
  DELETE_PROFILES: "DELETE_PROFILES",
  CREATE_PROFILES_POINTS_OF_SALE: "CREATE_PROFILES_POINTS_OF_SALE",
  UPDATE_PROFILES_POINTS_OF_SALE: "UPDATE_PROFILES_POINTS_OF_SALE",
  DELETE_PROFILES_POINTS_OF_SALE: "DELETE_PROFILES_POINTS_OF_SALE",

  // Coverages
  VIEW_COVERAGES: "VIEW_COVERAGES",
  VIEW_COVERAGES_REFERENCES: "VIEW_COVERAGES_REFERENCES",
  CREATE_COVERAGES: "CREATE_COVERAGES",
  UPDATE_COVERAGES: "UPDATE_COVERAGES",
  DELETE_COVERAGES: "DELETE_COVERAGES",

  // Coverage Durations
  VIEW_COVERAGE_DURATIONS: "VIEW_COVERAGE_DURATIONS",
  CREATE_COVERAGE_DURATIONS: "CREATE_COVERAGE_DURATIONS",
  UPDATE_COVERAGE_DURATIONS: "UPDATE_COVERAGE_DURATIONS",
  DELETE_COVERAGE_DURATIONS: "DELETE_COVERAGE_DURATIONS",

  // Insured Registries
  VIEW_INSURED_REGISTRIES: "VIEW_INSURED_REGISTRIES",
  CREATE_INSURED_REGISTRIES: "CREATE_INSURED_REGISTRIES",
  UPDATE_INSURED_REGISTRIES: "UPDATE_INSURED_REGISTRIES",
  DELETE_INSURED_REGISTRIES: "DELETE_INSURED_REGISTRIES",

  // Production Registries
  VIEW_PRODUCTION_REGISTRIES: "VIEW_PRODUCTION_REGISTRIES",
  CREATE_PRODUCTION_REGISTRIES: "CREATE_PRODUCTION_REGISTRIES",
  UPDATE_PRODUCTION_REGISTRIES: "UPDATE_PRODUCTION_REGISTRIES",
  DELETE_PRODUCTION_REGISTRIES: "DELETE_PRODUCTION_REGISTRIES",

  // Closures
  VIEW_CLOSURES: "VIEW_CLOSURES",
  CREATE_CLOSURES: "CREATE_CLOSURES",
  UPDATE_CLOSURES: "UPDATE_CLOSURES",
  DELETE_CLOSURES: "DELETE_CLOSURES",


  // Attestations Demandes
  VIEW_ATTESTATIONS_DEMANDS: "VIEW_ATTESTATIONS_DEMANDS",
  CREATE_ATTESTATIONS_DEMANDS_TO_MARKET_LEVEL_ORGANIZATION: "CREATE_ATTESTATIONS_DEMANDS_TO_MARKET_LEVEL_ORGANIZATION",
  CREATE_ATTESTATIONS_DEMANDS_TO_COMPANY: "CREATE_ATTESTATIONS_DEMANDS_TO_COMPANY",
  UPDATE_ATTESTATIONS_DEMANDS: "UPDATE_ATTESTATIONS_DEMANDS",
  DELETE_ATTESTATIONS_DEMANDS: "DELETE_ATTESTATIONS_DEMANDS",

  // Attestations (actions)
  VIEW_ATTESTATIONS: "VIEW_ATTESTATIONS",
  CREATE_ATTESTATIONS: "CREATE_ATTESTATIONS",
  DELIVER_ATTESTATIONS: "DELIVER_ATTESTATIONS",
  DELIVER_ATTESTATIONS_TO_POINTS_OF_SALE: "DELIVER_ATTESTATIONS_TO_POINTS_OF_SALE",
  DELIVER_ATTESTATIONS_TO_COMPANY: "DELIVER_ATTESTATIONS_TO_COMPANY",
  DISTRIBUTE_ATTESTATIONS: "DISTRIBUTE_ATTESTATIONS",
  REVOKE_ATTESTATIONS: "REVOKE_ATTESTATIONS",
  // Nouvelles permissions
    VIEW_STOCK_CENTRAL: 'VIEW_STOCK_CENTRAL',
    VIEW_COMMANDES: 'VIEW_COMMANDES',
    VIEW_ATTRIBUTION_COMPAGNIES: 'VIEW_ATTRIBUTION_COMPAGNIES',
    VIEW_ATTRIBUTION_PDV: 'VIEW_ATTRIBUTION_PDV',
    VIEW_RETRAIT_STOCKS: 'VIEW_RETRAIT_STOCKS',
    VIEW_SUIVI_ATTESTATIONS: 'VIEW_SUIVI_ATTESTATIONS'
};