name: Angular CI/CD
on:
  push:
    branches: laminef-deploy-dev-11/07/2025
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/*
  deploy:
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/laminef-deploy-dev-11/07/2025' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
      # - name: List downloaded artifact files
      #   run: |
      #     echo "Listing contents of the downloaded artifact folder:"
      #     ls -l /home/runner/work/${{ secrets.SERVER_USER }}/${{ secrets.SERVER_USER }}/
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add SSH key to known hosts
        run: >
          mkdir -p ~/.ssh

          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: >
          scp -P ${{ secrets.SERVER_PORT }} -r olive_front/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/olive_dev/webapps/olive_front/
